config/routes.rb
Rails.application.routes.draw do
  root 'about#index'
  devise_for :users
  resources :lists
  get 'lists/index'
  get 'home/trash_em'
  get 'home/trash_em_all'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :lists

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base




end
	

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def trash_em
	  @trash_em = List.where(:completed => true).destroy_all
	  redirect_to lists_url, notice: 'All Marked items have been deleted!!'
	end

	def trash_em_all
		@trash_em_all = List.all.destroy_all
		redirect_to lists_url, notice: 'All items have been deleted!!'

	end

 end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy, :show]

  # GET /lists or /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1 or /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    #@list = List.new
    @list = current_user.lists.build
  end

  # GET /lists/1/edit
  def edit
  end

  def correct_user
    @list = current_user.lists.find_by(id: params[:id])
    redirect_to lists_url, notice: "Not Authorized to handle this Task!!" if @list.nil? 
  end

  # POST /lists or /lists.json
  def create
    #@list = List.new(list_params)
    @list = current_user.lists.build(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to lists_url, notice: "List was successfully created." }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1 or /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to lists_url, notice: "List was successfully updated." }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1 or /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: "List was successfully destroyed." }
      format.json { head :no_content }
    end
  end





  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.require(:list).permit(:description, :completed, :user_id)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/about/index.html.erb
<h1>Hello All!</h1>
<h3>
<p>This is a fun little To-do list app in which you can manage your task list, cross-them, uncross-them and etc. Not much of the moving parts in this little RoR app But it is good to go!!. No other person can edit out your stuff or delete them. This remains confedential for even us to have a glance at your work.</p> 

<p>Safety remains on your end. Cancel your account if you sense someone mishandling your database records, though it is unlikely to happen. Never speak out your usernames and passwords. You, will be given a new workspace from out database which will seperate you out from other users. In this app  you will have even a confedential Username!! Therefore, you are always advised to create strong passwords.
</p>
<p>This website is created using Sublime Text Edit and Git Bash. Also, this website is hoisted on the network (or Internet) by heroku.</p>
<p>Sign up and begin with!!</p>
</h3>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <title>To-Do List App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <%= render 'lists/header' %>
    <div class="container">
      <% if notice %>
        <%= render 'lists/flash' %>
       <% end %>
       <br><br>
    <%= yield %>
  </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>



    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/lists/_flash.html.erb
<br>

<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/lists/_form.html.erb
<%= form_with(model: list) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <% form.label :description %>
    <%= form.text_field :description, class: "form-control", placeholder: 'Task Name' %>
  </div>

  <div class="field form-group">
    <%= form.number_field :user_id, id: :list_user_id, class:"form-control", value: current_user.id,type: :hidden %>
  </div>

  <div class="field">
    <% form.label :completed %>
    <% form.check_box :completed %>
  </div>
<br>
  <div class="actions form-group">
    <%= form.submit class: "btn btn-secondary"%>
  </div>
<% end %>

app/views/lists/_form_index.html.erb
<%= form_with(model: list) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  

<div class="form-inline my-2 my-lg-0">
  <%= f.text_field :description, class: 'form-control mr-sm-2' %>

  <%= f.submit "Add Todo Item", class: 'btn btn-outline-secondary my-2 my-lg-0'%>

</div>
 
<% end %>

app/views/lists/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" >To-do list app</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
        <%= link_to "View Your List", lists_path, class: 'nav-link active' %>
        <%= link_to "Edit Your Profile", edit_user_registration_path, class:"nav-link" %>
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
        <% else %>
        <%= link_to "Log In", new_user_session_path, class: 'nav-link active' %>
        <%= link_to "Register", new_user_registration_path, class: 'nav-link active' %>
        <% end %>
      </ul>
      
     
    </div>
  </div>
</nav>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<header>
  Signed in as: <%= current_user.email %></p>
  <p><br>
    <div class="btn-group" role="group" aria-label="Basic example">
<%= link_to 'New Task', new_list_path, class: "btn btn-secondary" %>
<%= link_to 'Delete all Crossed items', home_trash_em_path, class: 'btn btn-secondary' %>
<%= link_to 'Delete all items', home_trash_em_all_path, class: 'btn btn-secondary' %>
</div>


</header>
<hr><br>

<table class="table  table-bordered able-hovert">
  <thead class="table-dark">
    
  </thead>

  <tbody>
    <% @lists.each do |list| %>
    <% if list.user == current_user %>
    <% if list.completed %>
      <tr class="table-secondary">
        <td class="striker"><%=  list.description %></td>
        
       <td> 
          <center>
            <%= form_for(list) do |f| %>
            <%= f.text_field :description, type: 'hidden'%>
            <%= f.check_box :completed, :checked => false, :style => 'visibility: hidden'%>
            <%= f.submit "Uncross", class: "btn btn-outline-secondary btn-sm" %>
            <% end %>
          </center>
          
        </td>
        <td><%= link_to 'Delete', list, method: :delete, data: { confirm: 'Are you sure?' },  class: "btn btn-outline-danger btn-sm" %></td>
        <% else %>
        <tr >
        <td><%=  list.description %></td>
        
        <td>
          <center>
            <%= form_for(list) do |f| %>
            <%= f.text_field :description, type: 'hidden'%>
            <%= f.check_box :completed, :checked => true, :style => 'visibility: hidden'%>
            <%= f.submit "Cross off", class: "btn btn-outline-secondary btn-sm" %>
            <% end %>
          </center>
        </td>
        <td><%= link_to 'Delete', list, method: :delete, data: { confirm: 'Are you sure?' },  class: "btn btn-outline-danger btn-sm"%></td>
        <% end %>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

<br>
<center>


</center>

app/views/lists/new.html.erb
<div class="card">
	
<h4 class="card-header">New List</h4>
<div class="container">
<p class="card-text">
<%= render 'form', list: @list %>
</p>
</div>
</div>

app/views/lists/show.html.erb
<p>
  <strong>Description:</strong>
  <%= @list.description %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @list.completed %>
</p>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>